<a href="https://colab.research.google.com/github/midnight-koffee/mlneuro-learning/blob/main/tensorbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import torch

Step 1: Create Tensors

Define two tensors A and B, each of shape (2, 2). Fill them with different numbers so they’re easy to distinguish.

In [3]:
A = torch.ones(2,2)
B = torch.rand(2,2)

Task 1: Concatenation
1.1 Concatenate A and B along dim=0.

    What is the resulting shape?

    What do the rows look like?

1.2 Concatenate A and B along dim=1.

    What is the resulting shape?

    Where do the values of B appear in the output?

In [4]:
# we have to concatenate A and B along rows
ans1 = torch.cat([A,B], dim=0)
print(ans1)

tensor([[1.0000, 1.0000],
        [1.0000, 1.0000],
        [0.0504, 0.3768],
        [0.5831, 0.3082]])


In [5]:
ans2 = torch.cat([A,B], dim=1)
print(ans2)

tensor([[1.0000, 1.0000, 0.0504, 0.3768],
        [1.0000, 1.0000, 0.5831, 0.3082]])


Task 2: Stack
2.1 Stack A and B along dim=0, dim=1, and dim=2.

    What’s the shape each time?

    What happens to the rank (number of dimensions)?

In [6]:
anstack1 = torch.stack([A,B], dim=0)

In [7]:
anstack2 = torch.stack([A,B], dim = 1)
anstack3 = torch.stack([A,B],dim=2)

In [8]:
print(anstack1,anstack2,anstack3)
print(anstack1.shape,anstack2.shape,anstack3.shape)



tensor([[[1.0000, 1.0000],
         [1.0000, 1.0000]],

        [[0.0504, 0.3768],
         [0.5831, 0.3082]]]) tensor([[[1.0000, 1.0000],
         [0.0504, 0.3768]],

        [[1.0000, 1.0000],
         [0.5831, 0.3082]]]) tensor([[[1.0000, 0.0504],
         [1.0000, 0.3768]],

        [[1.0000, 0.5831],
         [1.0000, 0.3082]]])
torch.Size([2, 2, 2]) torch.Size([2, 2, 2]) torch.Size([2, 2, 2])


tensor = torch.arange(16).reshape(4, 4)
# Q: Set the last row to all 0s
# Q: Extract the diagonal elements manually using indexing
# Q: Replace second column with [1, 2, 3, 4]


In [18]:
tensor = torch.arange(16).reshape(4,4)
print(tensor)
tensor[3,:] = 0
print(tensor)
diag = torch.ones(1,4)
print(diag)
for i in range(4):
  diag[0][i] = tensor[i][i]
print(diag)

for j in range(4):
  tensor[j,1] = j+1
print(tensor)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  0,  0,  0]])
tensor([[1., 1., 1., 1.]])
tensor([[ 0.,  5., 10.,  0.]])
tensor([[ 0,  1,  2,  3],
        [ 4,  2,  6,  7],
        [ 8,  3, 10, 11],
        [ 0,  4,  0,  0]])


a = torch.ones(2, 3)
b = torch.zeros(2, 3)
# Q: Concatenate them row-wise (dim=0) → shape?
# Q: Concatenate them column-wise (dim=1) → shape?
# Q: Stack them along new dimension dim=0 → shape?


In [23]:
a = torch.ones(2, 3)
b = torch.zeros(2, 3)
# Q: Concatenate them row-wise (dim=0) → shape?
c = torch.cat([a,b], dim = 0)
print(c)
d = torch.cat([a,b], dim = 1)
print(d)
e = torch.stack([a,b], dim=0)
print(e)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


A = torch.tensor([[1., 2.], [3., 4.]])
B = torch.tensor([[2., 0.], [1., 2.]])
# Q: Compute A @ B
# Q: Use torch.matmul to do the same


In [29]:
A = torch.tensor([[1., 2.], [3., 4.]])
B = torch.tensor([[2., 0.], [1., 2.]])
# Q: Compute A @ B
C = A@B
print(C)
# Q: Use torch.matmul to do the same
D = torch.rand([2,2])
print(D)
torch.matmul(A,B, out=D)
print(D)


tensor([[ 4.,  4.],
        [10.,  8.]])
tensor([[0.3178, 0.7089],
        [0.5420, 0.2244]])
tensor([[ 4.,  4.],
        [10.,  8.]])


In [33]:
x = torch.tensor([[1., 2.], [3., 4.]])
# Q: Compute x * x
y = x*x
print(y)
d = torch.mul(x, x,out=torch.empty_like(x))
print(d)


# Q: Use torch.mul(x, x) with out=torch.empty_like(x)


tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])


In [40]:
x = torch.tensor([[1., 2.], [3., 4.]])
# Q: Sum all elements and extract as Python float
summ = x.sum()
print(summ)
print(type(summ))
pythoned = summ.item()
print(pythoned)
print(type(pythoned))
# Q: Mean all elements and print its type
meany = pythoned/4
print("The mean is", meany)
print(type(meany))

tensor(10.)
<class 'torch.Tensor'>
10.0
<class 'float'>
The mean is 2.5
<class 'float'>


In [43]:
x = torch.tensor([[1., 2.], [3., 4.]])
# Q: Add 10 to all elements using in-place op
x.add_(10)
# Q: Replace x with a new tensor (copy_): torch.tensor([[0., 0.], [0., 0.]])
x.mul_(0)


tensor([[0., 0.],
        [0., 0.]])