<a href="https://colab.research.google.com/github/midnight-koffee/mlneuro-learning/blob/main/tensorbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import torch

Step 1: Create Tensors

Define two tensors A and B, each of shape (2, 2). Fill them with different numbers so they’re easy to distinguish.

In [ ]:
A = torch.ones(2,2)
B = torch.rand(2,2)

Task 1: Concatenation
1.1 Concatenate A and B along dim=0.

    What is the resulting shape?

    What do the rows look like?

1.2 Concatenate A and B along dim=1.

    What is the resulting shape?

    Where do the values of B appear in the output?

In [ ]:
# we have to concatenate A and B along rows
ans1 = torch.cat([A,B], dim=0)
print(ans1)

tensor([[1.0000, 1.0000],
        [1.0000, 1.0000],
        [0.7089, 0.6990],
        [0.1772, 0.5298]])


In [ ]:
ans2 = torch.cat([A,B], dim=1)
print(ans2)

tensor([[1.0000, 1.0000, 0.7089, 0.6990],
        [1.0000, 1.0000, 0.1772, 0.5298]])


Task 2: Stack
2.1 Stack A and B along dim=0, dim=1, and dim=2.

    What’s the shape each time?

    What happens to the rank (number of dimensions)?

In [ ]:
anstack1 = torch.stack([A,B], dim=0)

In [ ]:
anstack2 = torch.stack([A,B], dim = 1)
anstack3 = torch.stack([A,B],dim=2)

In [ ]:
print(anstack1,anstack2,anstack3)
print(anstack1.shape,anstack2.shape,anstack3.shape)



tensor([[[1.0000, 1.0000],
         [1.0000, 1.0000]],

        [[0.7089, 0.6990],
         [0.1772, 0.5298]]]) tensor([[[1.0000, 1.0000],
         [0.7089, 0.6990]],

        [[1.0000, 1.0000],
         [0.1772, 0.5298]]]) tensor([[[1.0000, 0.7089],
         [1.0000, 0.6990]],

        [[1.0000, 0.1772],
         [1.0000, 0.5298]]])
torch.Size([2, 2, 2]) torch.Size([2, 2, 2]) torch.Size([2, 2, 2])
