<a href="https://colab.research.google.com/github/midnight-koffee/mlneuro-learning/blob/main/torchy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("let's see if it works")

let's see if it works


In [2]:
import torch
import numpy as np

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0140, 0.8348],
        [0.4794, 0.5345]]) 



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6391, 0.3561, 0.5575],
        [0.8084, 0.3828, 0.7390]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [8]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


🔢 1. Indexing & Slicing
🧩 Problem:

Create a 5×5 tensor filled with 7s. Then:

    Replace the third row with all zeros.

    Replace the last column with increasing numbers from 1 to 5.

    Extract and print the top-left 3×3 block.

In [17]:
tostart = torch.ones(5,5)
theseven = tostart*7
print(theseven)

fir = theseven
fir[3] = 0

for i in range(5):
    fir[i][-1] = i+1

print(fir)

print(fir[0:3,0:3])



tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])
tensor([[7., 7., 7., 7., 1.],
        [7., 7., 7., 7., 2.],
        [7., 7., 7., 7., 3.],
        [0., 0., 0., 0., 4.],
        [7., 7., 7., 7., 5.]])
tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])
